### ISSUE TITLE
How to get rid of debug messages?

### ISSUE THREAD

**Issue by the-overdriven** [fyryNy/zHackChest#1]
After trying to open a chest with a strength hotkey (T) it leaves debug messages above the chest, which never disappears:
![image](https://github.com/fyryNy/zHackChest/assets/100090726/d21acf47-6de5-454d-a318-14d8466a7ffd)

How can we prevent displaying these messages? Is it due to global Union's debug flag being turned on?

**Comment by fyryNy** [comment]
Turn off marvin mode
